# list
# ...
print("\n<<<<<<<<<<<<<<<<<<<<list>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n")
#set
a=[1,2,3,3,1]
b=[9,8]
print(a)
a.append(5)
print(a)
print(a.count(1))
a.insert(7,0)
print(a)
print(len(a))
a.extend(b)
print(a)
print(min(a))
print(max(a))
print(sum(a))
print(a.index(1,2))
a.reverse()
print(a)
a.sort()
print(a)
a.pop()
print(a)
a.remove(8)
print(a)
#print(del.a(1))
a.clear()
print(a)
#
print("\n<<<<<<<<<<<<<<<<<<<<dict>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n")
#set
# dictionary
d={1:10,2:20,3:30}
print(d)
print(list(d.keys()))
print(d.values())
print(d[1])
d[1]=100
print(d[1])
d1={1:244}                                        
d.update(d1)
print(d)
print(">",d.popitem())
d.pop(1)
print(d)
print("\n<<<<<<<<<<<<<<<<<<<<set>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n")
#set
s={1,2,3,4,5}
e={1,2,3}
print(s&e)
print(s|e)
print(s-e)
print(s^e)   
print(all(s))
print(any(s))
s.difference_update()
print(s)
print(sum(s))

print(min(s),max(s))
# print(a.isdisjoint(e))
print(s.issubset(e))
print(s.issuperset(e))