
print("\n*********************************\n")
def add():
    print("enter values for addition : ")
    a=int(input("1st value : "))
    b=int(input("2nd value : "))
    return(a+b)
c=add()
print(f"addition of a and  b is {c}")
print("\n*********************************\n")
def sub():
    print("enter values for subtraction: ")
    a=int(input("1st value : "))
    b=int(input("2nd value : "))
    return(a-b)
c=sub()
print(f"subtraction of a and  b is {c}")
print("\n*********************************\n")
def multi():
    print("enter values for multiplication : ")
    a=int(input("1st value : "))
    b=int(input("2nd value : "))
    return(a*b)
c=multi()
print(f"multiplication of a and  b is {c}")
print("\n*********************************\n")
def div():
    print("enter values for division : ")
    a=int(input("1st value : "))
    b=int(input("2nd value : "))
    return(a/b)
c=div()
print(f"division of a and  b is {c}")
print("\n*********************************\n")
def ep():
    print("enter values for exponent : ")
    a=int(input("1st value : "))
    b=int(input("2nd value : "))
    return(a**b)
c=ep()
print(f"exponent of a and  b is {c}")
print("\n*********************************\n")
def floor_div():
    print("enter values for floor division : ")
    a=int(input("1st value : "))
    b=int(input("2nd value : "))
    return(a//b)
c=floor_div()
print(f"floor division of a and b is {c}")
print("\n*********************************\n")
def modulo():
    print("enter values for modulo : ")
    a=int(input("1st value : "))
    b=int(input("2nd value : "))
    return(a%b)
c=modulo()
print(f"modulo of a and  b is {c}")
print("\n*********************************\n")
